# Generated by Django 3.1.5 on 2021-02-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('capacity', models.IntegerField(default=3, verbose_name='制限人数')),
                ('time', models.IntegerField(default=8, verbose_name='制限時間')),
                ('at', models.DateTimeField(verbose_name='作成日時')),
            ],
        ),
    ]
