# Generated by Django 3.1.5 on 2021-02-13 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='participants_num',
            field=models.IntegerField(default=0, verbose_name='参加人数'),
        ),
    ]
