# Generated by Django 3.1.5 on 2021-02-13 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_room_participants_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時'),
        ),
    ]
